"""Render the curriculum and interest registry as a Markdown review document.

    venv\\Scripts\\python.exe scripts\\curriculum_report.py

Writes `content/CURRICULUM.md`. The YAML files are the source of truth; this
document is generated from them so the reviewed copy can never drift from what
the app actually loads. Re-run it after every curriculum edit.
"""

from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT))

from src.curriculum.interests import load_interests  # noqa: E402
from src.curriculum.loader import all_concepts, load_subject  # noqa: E402

OUT = _ROOT / "content" / "CURRICULUM.md"
FORMATS = 3


def main() -> None:
    subject = load_subject(_ROOT / "data" / "curriculum" / "physics.yaml")
    interests = load_interests()
    concepts = all_concepts(subject)
    by_id = {c.id: c for c in concepts}
    chapters = [ch for u in subject.units for ch in u.chapters]
    chapter_seq = {ch.id: i for i, ch in enumerate(chapters, start=1)}

    lines: list[str] = []
    w = lines.append

    w("# EcoLearn curriculum — Class 11 + 12 Physics")
    w("")
    w("> Generated by `scripts/curriculum_report.py` from `data/curriculum/physics.yaml` "
      "and `data/interests.yaml`. **Do not edit by hand** — edit the YAML and re-run.")
    w("")
    n11 = sum(1 for c in concepts if c.grade == 11)
    n12 = len(concepts) - n11
    lessons = len(concepts) * len(interests) * FORMATS
    w(f"**{len(chapters)} chapters · {len(concepts)} concepts** (Class 11: {n11}, "
      f"Class 12: {n12}) × **{len(interests)} interests** × **{FORMATS} formats** "
      f"= **{lessons:,} lessons**.")
    w("")

    def board_label(c) -> str:
        values = sorted(b.value for b in c.boards)
        if values == ["cbse", "isc"]:
            return "CBSE + ISC"
        return " + ".join(v.upper() for v in values) or "Enrichment"

    w("Verified against the official CBSE 2025-26 syllabus. Every concept is on "
      "both boards unless listed below. ISC-only topics come from a third-party "
      "summary of the ISC syllabus — verify them against the official CISCE PDF.")
    w("")
    noted = [c for c in concepts if c.syllabus_note]
    if noted:
        w("## Board-specific and bridge concepts")
        w("")
        w("| Chapter | Concept | Boards | Note |")
        w("|---|---|---|---|")
        for c in noted:
            ch = next(ch for ch in chapters if ch.id == c.chapter_id)
            w(f"| {ch.name} | {c.name} (`{c.id}`) | {board_label(c)} | {c.syllabus_note} |")
        w("")

    w("## Interests")
    w("")
    w("| | Interest | Id | Natural fit for | Status |")
    w("|---|---|---|---|---|")
    for i in interests:
        doms = ", ".join(d.value for d in i.strong_domains)
        w(f"| {i.emoji} | {i.label} | `{i.id}` | {doms} | {i.status.value} |")
    w("")

    w("## Chapter overview")
    w("")
    w("| # | Class | Chapter | Domain | Concepts | Best-fit interests |")
    w("|---|---|---|---|---|---|")
    for ch in chapters:
        fits = ", ".join(i.label for i in interests
                         if any(d.value == ch.domain.value for d in i.strong_domains))
        w(f"| {chapter_seq[ch.id]} | {ch.grade} | {ch.name} | {ch.domain.value} | "
          f"{len(ch.concepts)} | {fits or '—'} |")
    w("")

    w("## Concepts by chapter")
    w("")
    w("Prerequisites marked ↩ come from an earlier chapter.")
    for unit in subject.units:
        for ch in unit.chapters:
            w("")
            w(f"### {chapter_seq[ch.id]}. {ch.name}")
            w(f"*Class {ch.grade} · Unit: {unit.name} · `{ch.id}`*")
            w("")
            w("| # | Concept | Prerequisites | Bloom | Learning objective |")
            w("|---|---|---|---|---|")
            for pos, c in enumerate(sorted(ch.concepts, key=lambda c: c.order), start=1):
                prereqs = []
                for pid in c.prerequisites:
                    p = by_id[pid]
                    mark = " ↩" if p.chapter_id != c.chapter_id else ""
                    prereqs.append(f"{p.name}{mark}")
                note = "" if board_label(c) == "CBSE + ISC" else f" *({board_label(c)})*"
                w(f"| {pos} | **{c.name}**{note}<br>`{c.id}` | {', '.join(prereqs) or '—'} | "
                  f"{c.bloom_target.value} | {c.learning_objective.strip()} |")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(_ROOT)}: {len(chapters)} chapters, "
          f"{len(concepts)} concepts, {lessons:,} lessons planned.")


if __name__ == "__main__":
    main()
